---
default_config:

homeassistant:
  internal_url: http://127.0.0.1:8123
  latitude: 48.1113387
  longitude: -1.6800198
  elevation: 38
  unit_system: metric
  time_zone: Europe/Paris
  name: Maison Démo
  allowlist_external_dirs:
    - /tmp

logger:
  default: warning
  logs:
    custom_components.ipx800: debug
    # homeassistant.components.automation: info

ipx800:
  - name: ipx800
    host: 192.168.1.240
    api_key: ezMYdvdsCpGiEda4w4Mp55SraTy
    username: user
    password: xJc3i9eradWVrL
    scan_interval: 10
    devices:
      - name: Chaudière
        icon: mdi:water-boiler
        type: "relay"
        component: "switch"
        id: 3
      - name: Lumière Garage
        type: relay
        component: light
        id: 9
      - name: Lumière Salle à Manger
        type: xdimmer
        component: light
        id: 1
      - component: light
        name: Spots Cuisine
        type: xpwm
        id: 1
      - component: light
        name: "Bandeau de LED Salon"
        type: xpwm_rgbw
        ids: [9, 10, 11, 12]
        transition: 1.5
      - component: binary_sensor
        device_class: motion
        name: Présence Cuisine
        type: virtualout
        id: 1
      - component: binary_sensor
        name: Sonnette
        type: digitalin
        icon: mdi:bell-circle-outline
        id: 1
      - component: sensor
        device_class: illuminance
        name: Luminosité Cuisine
        icon: mdi:white-balance-sunny
        type: analogin
        id: 1
        unit_of_measurement: "lx"
      - component: sensor
        name: Capteur Rez-de-Chaussée
        type: xthl
        id: 1
      - component: cover
        name: Volet Salon
        type: x4vr
        ext_id: 1
        id: 1
