---
default_config:

homeassistant:
  internal_url: http://127.0.0.1:8123
  latitude: 48.1113387
  longitude: -1.6800198
  elevation: 38
  unit_system: metric
  time_zone: Europe/Paris
  name: Maison Démo
  allowlist_external_dirs:
    - /tmp

logger:
  default: warning
  logs:
    custom_components.ipx800: debug
    # homeassistant.components.automation: info

ipx800:
  - name: ipx800
    host: 192.168.1.240
    api_key: ezMYdvdsCpGiEda4w4Mp55SraTy
    username: user
    password: xJc3i9eradWVrL
    # scan_interval: 5
    devices:
      - name: "Lumière Bureau"
        type: "relay"
        component: "light"
        id: 15
      - name: "Carillon"
        icon: mdi:bell
        type: "relay"
        component: "switch"
        id: 5
      - name: "Lumière Chevet Matthieu"
        type: "xdimmer"
        component: "light"
        id: 4
      - component: light
        name: "Spots Couloir"
        type: xpwm
        id: 6
        transition: 0.8
      - component: switch
        name: IPX800 Mode Automatique
        icon: mdi:play-circle-outline
        type: virtualin
        id: 1
      - component: binary_sensor
        device_class: motion
        name: Présence Couloir
        type: virtualout
        id: 6
      - component: binary_sensor
        name: Etat Porte Garage
        type: digitalin
        id: 2
      - component: sensor
        device_class: illuminance
        name: Luminosité Salle de Bains
        icon: mdi:white-balance-sunny
        type: analogin
        id: 2
        unit_of_measurement: "lx"
      - component: sensor
        name: Capteur Salle à Manger
        type: xthl
        id: 1
        